language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - composer self-update
  - composer update --prefer-source --dev

script:
  - phpunit --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
